// Code generated by goctl. DO NOT EDIT.

export interface AuthCodeRequest {}

export interface AuthCodeRequestParams {
  code: string;
}

export interface AuthCodeResponse {
  userId: string;
  address: string;
  channelId: string;
  serverId: string;
}

export interface ValidateServerPermissionsRequest {}

export interface ValidateServerPermissionsRequestParams {
  serverId: string;
  userId: string;
  group: string;
  permissions: string;
}

export interface ValidateServerPermissionsResponse {
  allowed: string;
}

export interface ValidateChannelPermissionsRequest {}

export interface ValidateChannelPermissionsRequestParams {
  channelId: string;
  userId: string;
  group: string;
  permissions: string;
}

export interface ValidateChannelPermissionsResponse {
  allowed: string;
}

export interface NotificationContent {
  sender: string;
}

export interface NotifyRequest {
  channelId: string;
  title: string;
  content: string;
  jumpPath: string;
  receiverIds?: Array<string>; // when this parameter is not passed, everyone in the channel will be notified by default; otherwise, it will be notified by the specified user
}
